## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Hobyo,SO,5.3505,48.5268,76.10,81,95,30.89,overcast clouds
1,1,Maple Creek,CA,49.9168,-109.4848,89.65,25,0,6.91,clear sky
2,2,Puerto Ayora,EC,-0.7393,-90.3518,76.96,95,68,5.01,broken clouds
3,3,Ushuaia,AR,-54.8000,-68.3000,38.86,52,20,5.75,few clouds
4,4,Mumias,KE,0.3351,34.4864,63.59,91,72,3.29,light rain

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Hobyo,SO,5.3505,48.5268,76.10,81,95,30.89,overcast clouds
1,1,Maple Creek,CA,49.9168,-109.4848,89.65,25,0,6.91,clear sky
2,2,Puerto Ayora,EC,-0.7393,-90.3518,76.96,95,68,5.01,broken clouds
4,4,Mumias,KE,0.3351,34.4864,63.59,91,72,3.29,light rain
6,6,Rikitea,PF,-23.1203,-134.9692,73.65,81,86,14.65,moderate rain
7,7,Bethel,US,41.3712,-73.4140,84.65,64,0,8.05,clear sky
8,8,Jamestown,US,42.0970,-79.2353,71.94,94,100,10.36,thunderstorm with rain
13,13,Peniche,PT,39.3558,-9.3811,70.29,86,0,3.22,clear sky
14,14,Atuona,PF,-9.8000,-139.0333,78.08,77,11,20.69,few clouds
15,15,Tuktoyaktuk,CA,69.4541,-133.0374,62.60,72,40,10.36,scattered clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                452
City                   452
Country                448
Lat                    452
Lng                    452
Max Temp               452
Humidity               452
Cloudiness             452
Wind Speed             452
Current Description    452
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df=preferred_cities_df.dropna()

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Hobyo,SO,76.10,overcast clouds,5.3505,48.5268,
1,Maple Creek,CA,89.65,clear sky,49.9168,-109.4848,
2,Puerto Ayora,EC,76.96,broken clouds,-0.7393,-90.3518,
4,Mumias,KE,63.59,light rain,0.3351,34.4864,
6,Rikitea,PF,73.65,moderate rain,-23.1203,-134.9692,
7,Bethel,US,84.65,clear sky,41.3712,-73.4140,
8,Jamestown,US,71.94,thunderstorm with rain,42.0970,-79.2353,
13,Peniche,PT,70.29,clear sky,39.3558,-9.3811,
14,Atuona,PF,78.08,few clouds,-9.8000,-139.0333,
15,Tuktoyaktuk,CA,62.60,scattered clouds,69.4541,-133.0374,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.") 

hotel_df.head()

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Hobyo,SO,76.10,overcast clouds,5.3505,48.5268,Iftin hotel hobyo
1,Maple Creek,CA,89.65,clear sky,49.9168,-109.4848,Willowbend Campground & Cabins
2,Puerto Ayora,EC,76.96,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
4,Mumias,KE,63.59,light rain,0.3351,34.4864,Mumias Sugar Guesthouse
6,Rikitea,PF,73.65,moderate rain,-23.1203,-134.9692,People ThankYou

In [9]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df=hotel_df[hotel_df["Hotel Name"]!=None]
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Hobyo,SO,76.10,overcast clouds,5.3505,48.5268,Iftin hotel hobyo
1,Maple Creek,CA,89.65,clear sky,49.9168,-109.4848,Willowbend Campground & Cabins
2,Puerto Ayora,EC,76.96,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
4,Mumias,KE,63.59,light rain,0.3351,34.4864,Mumias Sugar Guesthouse
6,Rikitea,PF,73.65,moderate rain,-23.1203,-134.9692,People ThankYou
...,...,...,...,...,...,...,...
691,Bandarbeyla,SO,76.32,clear sky,9.4942,50.8122,JABIR HOTEL
692,Havre-Saint-Pierre,CA,66.56,few clouds,50.2334,-63.5986,Auberge Niapiskau
694,Arai,JP,75.92,overcast clouds,37.0167,138.2500,神の宮温泉 かわら亭
695,Foam Lake,CA,73.42,clear sky,51.6500,-103.5343,Fishing Lake Lodge LTD
696,Cotonou,BJ,76.44,few clouds,6.3654,2.4183,Novotel Cotonou Orisha

In [10]:
# 8a. Create the output File (CSV)
output_data_file= "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))